"""about_me and last_seen fields in user

Revision ID: 665e12e859cf
Revises: 22358e630c8c
Create Date: 2020-03-22 17:24:06.887926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665e12e859cf'
down_revision = '22358e630c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
